# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VMWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VMWorld
  pod 'Alamofire', '~> 4.7'

  target 'VMWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VMWorldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
